{% set name = "kfp-tekton" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kfp-tekton-{{ version }}.tar.gz
  sha256: b31e60eb5eb70009dcfe75e6327a0a546e06adf6dfc243593d8cb7f8a4bb60b7

build:
  number: 0
  noarch: python
  entry_points:
    - dsl-compile-tekton = kfp_tekton.compiler.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5.3
    - pip
    - requests
  run:
    - python >=3.5.3
    - kfp >=1.8.10,<1.8.12

test:
  imports:
    - kfp_tekton
    - kfp_tekton.compiler
  commands:
    - dsl-compile-tekton --help
  requires:
    - pip

about:
  home: https://github.com/kubeflow/kfp-tekton/
  summary: Tekton Compiler for Kubeflow Pipelines
  description: |
    The kfp-tekton SDK compiles Kubeflow Pipeline DSL scripts to
    Tekton PipelineRun CRDs which can be executed on a Kubernetes
    cluster.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/kubeflow/kfp-tekton/tree/master/sdk/python
  doc_url: https://www.kubeflow.org/docs/pipelines/sdk/pipelines-with-tekton
  doc_source_url: https://github.com/kubeflow/kfp-tekton/blob/master/sdk/README.md

extra:
  recipe-maintainers:
    - ckadner
    - Tomcli
    - animeshsingh
